### ISSUE TITLE
Error: name 'profile' is not defined

### ISSUE THREAD

**Issue by LuZhangstat** [marcinjurek/pyMRA#10]
I am a new user of pyMRA. I had the following error when I ran the example on GitHub:
<img width="582" alt="screen shot 2018-02-27 at 11 43 51 am" src="https://user-images.githubusercontent.com/23649581/36751782-fa25c4c4-1bb5-11e8-8d7c-9d810b7bbbcc.png">

Does anyone have any idea about this error? Thank you very much!

**Comment by marcinjurek** [comment]
Thanks, this was some artifact of the profiling I was doing. I fixed it and pushed a new update. Let me know if it still doesn't work but it should. Thanks for letting me know and for your interest in pyMRA!

**Comment by LuZhangstat** [comment]
Hi Marcin,

    Great, I can compile without the error report. Thank you very much! ^_^

Best,

Lu Zhang
